### ISSUE TITLE
Breaking changes in v2.0.0

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/py-algorand-sdk#384]
Itemizes functionality that will be removed in the upcoming major release.

Task list for algorand-sdk-testing stories:
- [x] https://github.com/algorand/algorand-sdk-testing/issues/201 - https://github.com/algorand/py-algorand-sdk/pull/412
- [x] https://github.com/algorand/algorand-sdk-testing/issues/202 - N/A no removal needed 
- [x] https://github.com/algorand/algorand-sdk-testing/issues/223 - https://github.com/algorand/py-algorand-sdk/pull/411
- [x] https://github.com/algorand/algorand-sdk-testing/issues/254 - https://github.com/algorand/py-algorand-sdk/pull/410
- [x] https://github.com/algorand/algorand-sdk-testing/issues/255 - https://github.com/algorand/py-algorand-sdk/pull/418
- [x] https://github.com/algorand/generator/issues/46 - N/A no generated source code

**Comment by algochoi** [comment]
Let's consider changing `wait_rounds` to match the other SDKs - when the value is zero, the other SDKs wait zero rounds instead of 1000 (e.g. [JS](https://github.com/algorand/js-algorand-sdk/blob/develop/src/wait.ts)) 

Related PR: https://github.com/algorand/py-algorand-sdk/pull/380
